IF (AVRO_INCLUDE_DIR)
  # Already in cache, be silent
  SET(AVRO_FIND_QUIETLY TRUE)
ENDIF (AVRO_INCLUDE_DIR)

FIND_PATH(AVRO_INCLUDE_DIR Schema.hh
  /usr/local/include/avro
  /usr/include/avro
)

FIND_LIBRARY(AVRO_LIBRARIES
  NAMES avrocpp
  PATHS /usr/lib /usr/local/lib /usr/lib64
)

IF (AVRO_INCLUDE_DIR AND AVRO_LIBRARIES)
    SET(AVRO_FOUND TRUE)
ELSE (AVRO_INCLUDE_DIR AND AVRO_LIBRARIES)
    SET(AVRO_FOUND FALSE)
ENDIF (AVRO_INCLUDE_DIR AND AVRO_LIBRARIES)

IF (AVRO_FOUND)
    IF (NOT AVRO_FIND_QUIETLY)
        message(STATUS "Avro found in ${AVRO_LIBRARIES}")
    ENDIF (NOT AVRO_FIND_QUIETLY)
ELSE(AVRO_FOUND)
    IF (AVRO_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could NOT found avro library")
    ENDIF(AVRO_FIND_REQUIRED)
ENDIF(AVRO_FOUND)


MARK_AS_ADVANCED(
    AVRO_LIBRARIES
    AVRO_INCLUDE_DIR
  )
